# Generated by Django 2.2.2 on 2019-06-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    
    ]
