# Generated by Django 2.2.4 on 2020-04-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcurriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeempresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=80)),
                ('objetos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecurso', models.CharField(max_length=100)),
                ('textdescricao', models.TextField()),
            ],
        ),
    ]
